### ISSUE TITLE
Needs children, not left and right.

### ISSUE THREAD

**Issue by dakamojo** [beagle-barks/material_segmented_control#1]
When I saw this component I was pleased but then saw that it only supported two children.  To implement the Material Toggle Button it clearly needs to support a children array rather than just a left and right child.

**Comment by benjamin-kraatz** [comment]
You're right! Work is already in progress!

**Comment by benjamin-kraatz** [comment]
Now available with version 1.0.0. Check out [pub.dev package](https://pub.dev/packages/material_segmented_control) or clone it.

Thanks!
