### ISSUE TITLE
Unable to run the example code

### ISSUE THREAD

**Issue by bigbang489** [beagle-barks/material_segmented_control#11]
I got the bellow error when try to run your example:

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Xcode build done.                                           10.4s
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building DefaultTextStyle(debugLabel: (englishLike body1
flutter: 2014).merge(blackCupertino body1), inherit: false, color: Color(0xdd000000), family: .SF UI Text,
flutter: size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping
flutter: at box width, overflow: clip):
flutter: 'package:material_segmented_control/material_segmented_control.dart': Failed assertion: line 470 pos
flutter: 16: 'textDirection != null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   Material
[38;5;248mflutter:[39;49m
flutter:
flutter: When the exception was thrown, this was the stack:
[38;5;248mflutter: #2      new _RenderSegmentedControl[39;49m
[38;5;248mflutter: #3      _SegmentedControlRenderWidget.createRenderObject[39;49m
[38;5;244mflutter: #4      RenderObjectElement.mount[39;49m
[38;5;244mflutter: #5      MultiChildRenderObjectElement.mount[39;49m
[38;5;244mflutter: #6      Element.inflateWidget[39;49m
[38;5;244mflutter: #7      Element.updateChild[39;49m
[38;5;244mflutter: #8      SingleChildRenderObjectElement.mount[39;49m
[38;5;244mflutter: #9      Element.inflateWidget[39;49m
[38;5;244mflutter: #10     Element.updateChild[39;49m
[38;5;244mflutter: #11     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mflutter: #12     Element.inflateWidget[39;49m
[38;5;244mflutter: #13     Element.updateChild[39;49m
[38;5;244mflutter: #14     ComponentElement.performRebuild[39;49m
[38;5;244mflutter: #15     Element.rebuild[39;49m
[38;5;244mflutter: #16     ComponentElement._firstBuild[39;49m
[38;5;244mflutter: #17     ComponentElement.mount[39;49m
[38;5;244mflutter: #18     Element.inflateWidget[39;49m
[38;5;244mflutter: #19     Element.updateChild[39;49m
[38;5;244mflutter: #20     ComponentElement.performRebuild[39;49m
[38;5;244mflutter: #21     Element.rebuild[39;49m
[38;5;244mflutter: #22     ComponentElement._firstBuild[39;49m
[38;5;244mflutter: #23     StatefulElement._firstBuild[39;49m
[38;5;244mflutter: #24     ComponentElement.mount[39;49m
[38;5;244mflutter: #25     Element.inflateWidget[39;49m
[38;5;244mflutter: #26     Element.updateChild[39;49m
[38;5;244mflutter: #27     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mflutter: #28     Element.inflateWidget[39;49m
[38;5;244mflutter: #29     Element.updateChild[39;49m
[38;5;244mflutter: #30     ComponentElement.performRebuild[39;49m
[38;5;244mflutter: #31     Element.rebuild[39;49m
[38;5;244mflutter: #32     ComponentElement._firstBuild[39;49m
[38;5;244mflutter: #33     ComponentElement.mount[39;49m
[38;5;244mflutter: #34     Element.inflateWidget[39;49m
[38;5;244mflutter: #35     Element.updateChild[39;49m
[38;5;244mflutter: #36     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mflutter: #37     Element.inflateWidget[39;49m
[38;5;244mflutter: #38     Element.updateChild[39;49m
[38;5;244mflutter: #39     ComponentElement.performRebuild[39;49m
[38;5;244mflutter: #40     Element.rebuild[39;49m
[38;5;244mflutter: #41     ComponentElement._firstBuild[39;49m
[38;5;244mflutter: #42     ComponentElement.mount[39;49m
[38;5;244mflutter: #43     Element.inflateWidget[39;49m
[38;5;244mflutter: #44     Element.updateChild[39;49m
[38;5;244mflutter: #45     ComponentElement.performRebuild[39;49m
[38;5;244mflutter: #46     Element.rebuild[39;49m
[38;5;244mflutter: #47     ComponentElement._firstBuild[39;49m
[38;5;244mflutter: #48     StatefulElement._firstBuild[39;49m
[38;5;244mflutter: #49     ComponentElement.mount[39;49m
[38;5;244mflutter: #50     Element.inflateWidget[39;49m
[38;5;244mflutter: #51     Element.updateChild[39;49m
[38;5;244mflutter: #52     ComponentElement.performRebuild[39;49m
[38;5;244mflutter: #53     Element.rebuild[39;49m
[38;5;244mflutter: #54     ComponentElement._firstBuild[39;49m
[38;5;244mflutter: #55     StatefulElement._firstBuild[39;49m
[38;5;244mflutter: #56     ComponentElement.mount[39;49m
[38;5;244mflutter: #57     Element.inflateWidget[39;49m
[38;5;244mflutter: #58     Element.updateChild[39;49m
[38;5;244mflutter: #59     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mflutter: #60     Element.inflateWidget[39;49m
[38;5;244mflutter: #61     Element.updateChild[39;49m
[38;5;244mflutter: #62     ComponentElement.performRebuild[39;49m
[38;5;244mflutter: #63     Element.rebuild[39;49m
[38;5;244mflutter: #64     ComponentElement._firstBuild[39;49m
[38;5;244mflutter: #65     ComponentElement.mount[39;49m
[38;5;244mflutter: #66     Element.inflateWidget[39;49m
[38;5;244mflutter: #67     Element.updateChild[39;49m
[38;5;244mflutter: #68     ComponentElement.performRebuild[39;49m
[38;5;244mflutter: #69     Element.rebuild[39;49m
[38;5;244mflutter: #70     ComponentElement._firstBuild[39;49m
[38;5;244mflutter: #71     StatefulElement._firstBuild[39;49m
[38;5;244mflutter: #72     ComponentElement.mount[39;49m
[38;5;244mflutter: #73     Element.inflateWidget[39;49m
[38;5;244mflutter: #74     Element.updateChild[39;49m
[38;5;244mflutter: #75     RenderObjectToWidgetElement._rebuild[39;49m
[38;5;244mflutter: #76     RenderObjectToWidgetElement.mount[39;49m
[38;5;244mflutter: #77     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>[39;49m
[38;5;244mflutter: #78     BuildOwner.buildScope[39;49m
[38;5;244mflutter: #79     RenderObjectToWidgetAdapter.attachToRenderTree[39;49m
[38;5;244mflutter: #80     WidgetsBinding.attachRootWidget[39;49m
[38;5;244mflutter: #81     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>[39;49m
[38;5;244mflutter: #90     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:384:19)[39;49m
[38;5;244mflutter: #91     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:418:5)[39;49m
[38;5;244mflutter: #92     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)[39;49m
flutter: (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
Test files:
main.dart:
import 'package:flutter/material.dart';
import 'package:material_segmented_control/material_segmented_control.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int _currentSelection = 0;

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: MaterialSegmentedControl(
          children: _children,
          selectionIndex: _currentSelection,
          borderColor: Colors.grey,
          selectedColor: Colors.redAccent,
          unselectedColor: Colors.white,
          borderRadius: 24.0,
          disabledChildren: [
            3,
          ],
          onSegmentChosen: (index) {
            setState(() {
              _currentSelection = index;
            });
          },
        ),
      ),
    );
  }

  Map<int, Widget> _children = {
    0: Text('Hummingbird'),
    1: Text('Kiwi'),
    2: Text('Rio'),
    3: Text('Telluraves')
  };
}

**Comment by benjamin-kraatz** [comment]
Thanks for your report! I fixed the example in the latest commit. Sorry for my late response, I was very busy.

Feel free to open another issue if somethings not working!
