### ISSUE TITLE
Box Border Line Offset on Flutter Web

### ISSUE THREAD

**Issue by Gizmo20004000** [beagle-barks/material_segmented_control#13]
Hi there, 

The widget works great but I have a minor offset of the border every time I use it. Any idea why this might happen?

Best Regards

![Unbenannt](https://user-images.githubusercontent.com/64018871/79755422-63ccab00-8319-11ea-9b42-4a4441c3e7b6.PNG)

**Comment by benjamin-kraatz** [comment]
Hey, thank you!

This is a weird thing I've never seen before.
Can you reproduce it everywhere you put the control, or just there?

Did you try to place it as the only and direct child of a Scaffold, what will happen?

I'm sure we'll find a solution!

**Comment by Gizmo20004000** [comment]
Hey beagle-barks,

thanks a lot for your fast response! I tried an empty page and got the same result. Im using flutter web.
![Unbenannt2](https://user-images.githubusercontent.com/64018871/79762580-38e75480-8323-11ea-9fa3-4e7c4d91dec9.PNG)


`import 'package:flutter/material.dart';
import 'package:material_segmented_control/material_segmented_control.dart';

class BlankTestScreen extends StatefulWidget {
  @override
  _BlankTestScreenState createState() => _BlankTestScreenState();
}

class _BlankTestScreenState extends State<BlankTestScreen> {
  Map<int, Widget> _children = {
  0: Text('Hummingbird'),
  1: Text('Kiwi'),
  2: Text('Rio'),
  3: Text('Telluraves')
};

  int _currentSelection = 0;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: Center(
        child: MaterialSegmentedControl(
          children: _children,
          selectionIndex: _currentSelection,
          borderColor: Colors.grey,
          selectedColor: Colors.redAccent,
          unselectedColor: Colors.white,
          borderRadius: 32.0,
          disabledChildren: [
            3,
          ],
          onSegmentChosen: (index) {
            setState(() {
              _currentSelection = index;
            });
          },
         ),
      ),
    );
  }
}`

**Comment by benjamin-kraatz** [comment]
Yes, you're right. I can reproduce it on Flutter Web.

Because it performs well on desktop and mobile, I think this is a (known?) bug in the web framework. There is probably no way for me to fix it.

Since it uses CustomPaint to draw the border, I've tried to reproduce this painting - and on web in some cases it behaves the same.

I think you should turn to Flutter to file an issue (if there isn't already one).


Sorry about that, but hopefully Web becomes stable as soon as possible!


I'll leave this issue open until there is a solution.

**Comment by Gizmo20004000** [comment]
What a pity! 

However we like your widget that much that we just gonna keep it until its fixed even though it doesnt look perfect yet!

Thanks a lot!

**Comment by benjamin-kraatz** [comment]
That's really nice to know, thank you!
Feel free to open another issue if something's not working.

**Comment by timobaehr** [comment]
Bug still there for Flutter Web.

**Comment by benjamin-kraatz** [comment]
Right, it is still there on Flutter Web - there is a workaround for this, but significantly less performant than it is currently. I'll create a preview version of it within the next days.

Please note that Flutter for Web is not production ready yet and still in [beta](https://flutter.dev/web)

**Comment by saeedszz** [comment]
Hi Use this Code 


Container(
                             child: MaterialSegmentedControl(
                               horizontalPadding: EdgeInsets.all(1),
                               verticalOffset: 15,
                               selectionIndex: _currentSelection,
                               borderColor: Colors.transparent,
                               selectedColor:Colors.cyan ,
                               unselectedColor:  purplecolor,
                               borderRadius: 30.0,
                               children: _children,
                               onSegmentChosen: (index) {
                                 setState(() {
                                   _currentSelection = index;
                                   tabController.index = index;
                                 });
                               },),
                             decoration: BoxDecoration(
                                 borderRadius: BorderRadius.all(Radius.circular(30)),
                                 border: Border.all(color: Colors.white,width: 3)
                             ),
                           ),



it will be like this

**Comment by benjamin-kraatz** [comment]
With Flutter 2 and Dart 2.12 this issue does no longer apply.
Please open another issue if this still appears.
