### ISSUE TITLE
feature request - all items disabled

### ISSUE THREAD

**Issue by SogoGolf** [beagle-barks/material_segmented_control#14]
hi, thanks for great control. any chance you could add a property that allowed us to have all of the options in the segmented control un-selected ?

**Comment by benjamin-kraatz** [comment]
Thanks! Nice feature. I'm working on it!

**Comment by benjamin-kraatz** [comment]
Just set `selectionIndex` to `null`. This clears the selection on all children.

This is already available and now showcased in the example project. Feel free to check it out. It is massively improved with version 2.1.0

Open another issue if anything is not working for you.

Thanks!
