### ISSUE TITLE
[BUG] Text selected/unselected color can't be customized

### ISSUE THREAD

**Issue by herrmartell** [beagle-barks/material_segmented_control#16]
Most of the things in [this issue](https://github.com/beagle-barks/material_segmented_control/issues/4) were fixed, but we are still unable to customize the text color when we have a custom style.

```dart
Map<int, Widget> options = {
    0: Text(
      'Today',
      style: muliRegular(
        color: ThemeColor.primaryDarkGrey,
        fontSize: 12.0,
      ),
    ),
    1: Text(
      'Week',
      style: muliRegular(
        color: ThemeColor.primaryDarkGrey,
        fontSize: 12.0,
      ),
    ),
    2: Text(
      'Month',
      style: muliRegular(
        color: ThemeColor.primaryDarkGrey,
        fontSize: 12.0,
      ),
    ),
  };
```

Expected
<img width="318" alt="Screen Shot 2020-12-11 at 11 30 49" src="https://user-images.githubusercontent.com/7809287/101935205-54e68180-3ba4-11eb-9c55-e964984728a3.png">

What we really get
<img width="368" alt="Screen Shot 2020-12-11 at 11 31 08" src="https://user-images.githubusercontent.com/7809287/101935230-5fa11680-3ba4-11eb-87b5-525400d9c200.png">

**Comment by beagle-barks** [comment]
As I can see in your code sample you are using gray colors for all of the texts. 
This, of course, sets all text colors to the same.

If you define the text color for a specific item based on `selectionIndex`.

**Comment by benjamin-kraatz** [comment]
As I can see in your code sample you are using gray colors for all of the texts.
This, of course, sets all text colors to the same.

You can define the text color for a specific item based on `selectionIndex`.
