### ISSUE TITLE
Not a segmented control

### ISSUE THREAD

**Issue by Nico04** [beagle-barks/material_segmented_control#3]
The idea of making a Material segmented control is great !
But I've tried your plugin v1.2, and it's not the behaviour I expect from a segmented control.

Apple says :
> segmented control is a linear set of two or more segments, each of which functions as a mutually exclusive button.

Here they are not mutually exclusive...
Is it the expected behaviour ?

**Comment by benjamin-kraatz** [comment]
Hi, thank you!

But, what do you mean by "mutually exclusive"?
Could you please explain, so that I can understand what that means in this context?

And what is the behaviour you expect, and the difference between this and msc's behaviour?

thanks in advance

**Comment by benjamin-kraatz** [comment]
Ok, I think I understand what you mean.
so, you're describing that a segment is not the only selectable segment?
I've never faced that issue. Could you provide me code and steps to reproduce?

**Comment by benjamin-kraatz** [comment]
Everything should work now with version 2.0.2 and newer. 
Please open another issue if something went wrong.

**Comment by Nico04** [comment]
I've tried the v2, it's much much better now, awesome !
Nice work :)

**Comment by benjamin-kraatz** [comment]
Thanks! Hope you enjoy :)
