### ISSUE TITLE
More customisation needed

### ISSUE THREAD

**Issue by Nico04** [beagle-barks/material_segmented_control#4]
I think there are many basic settings that are missing or doesn't work as expected :

1. Can't remove horizontal margin (vertical margin is zero)
	- When used inside a stretched Column or a fixed-width SizedBox
2. Can't set the height (even with a SizedBox) :
	- When bigger it just centers itselft
	- When smaller it overflows
3. Can't remove/set the vertical content padding (horizontal one is zero)
4. If child is a Text, by default it applies the selected/unselected colors well, but it doens't work anymore when we set a custom style to the Text widget.
	- As an example, it work as expected with the TabBar component using the TabBarTheme.labelStyle

Thank you for your work, it is very usefull to me :)

**Comment by benjamin-kraatz** [comment]
Thanks for your feedback!
I'm already working on this. Update is coming soon!

**Comment by benjamin-kraatz** [comment]
Ok, let's see.
The following applies to version [**2.0.6**](https://pub.dev/packages/material_segmented_control)

I hope anything of the following matches your points, if not please comment!

1. You can now customize your vertical padding of the children. *This also could mean 'setting the height of the widget' in most cases*.
Use **verticalOffset** parameter.

2. Setting a custom style works well in my case, I can set color and font size and weight without any problems. **What exactly does not work?**

3. Horizontal margin cannot be set directly, but you can use a fixed-width SizedBox to size it to your needs. 
If the width is greater than screen width, the widget should expand without overflow.
Even setting the width 'too small' did not cause an overflow in my case.
> *Of course, setting the **height** too small causes an overflow. You should set the height via **verticalOffset**.*


If something's not clear please comment and reopen.

Hope I can help you!
