### ISSUE TITLE
access null if not set selected collor

### ISSUE THREAD

**Issue by phammanh029** [beagle-barks/material_segmented_control#6]
i found that in code. if i unset selected color or unsetSelected color. Library will be crashed. (function _updateColors() in material_segmented_control.dart:153)
The following code cause that error: 
`final Color pressedColor = widget.selectedColor.withOpacity(0.2);`

this line of code should be selectedColor.withOpacity(0.2); or mark selectedColor as required in constructor

**Comment by benjamin-kraatz** [comment]
Fixed.
See version 2.0.4 and latest commit on master branch.

 Thanks for report!
