### ISSUE TITLE
Enabled/Disable feature

### ISSUE THREAD

**Issue by eitanaviv** [beagle-barks/material_segmented_control#9]
Hi there,
I think it would be nice having a enabled/disable feature built-in to the library :)

Thanks!

**Comment by benjamin-kraatz** [comment]
Thank you for this idea!

Work in progress!

**Comment by benjamin-kraatz** [comment]
You can check out new version [2.0.8](https://pub.dev/packages/material_segmented_control) from pub.dev!

**Comment by eitanaviv** [comment]
@beagle-barks Thanks for that fast feature development :)
But, I think something is not good with your asserts - I'm getting "Do not set disabled color to null if disabled children are defined" after upgrading the library and without adding anything, which means I haven't `disabledChildren` and `disabledColor` which should not give me any errors.
Am I right with this one?

**Comment by benjamin-kraatz** [comment]
@eitanaviv You're right, there is somehing wrong with the asserts. I'll fix it quickly. Thanks for you response!

**Comment by benjamin-kraatz** [comment]
This should now work as expected in version 2.0.9!
For any further questions, feature or bug reports, feel free to open another issue!

Thanks!

**Comment by eitanaviv** [comment]
Thanks!
Works great now :)
